[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
agent-core = { version = "0.1.0", path = "../core" }
dirs = "6.0.0"
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9.34"

[dev-dependencies]
serial_test = "3.2.0"
